CREATE TABLE `data_platform_quatation_for_smes_item_data`
(
		`ReferencedDocumentIssuerAssignedIdentificationIdentifier`          int(16) NOT NULL,
		`DocumentLineDocumentLineIdentifier`                                int(16) DEFAULT NULL,                                                    								
		`DocumentLineDocumentLineStatusCode`                                int(4) DEFAULT NULL,				           	
		`NoteSubjectText`                                                   varchar(200) DEFAULT NULL,								           
		`NoteContentText`                                                   varchar(200) DEFAULT NULL,								
		`NoteIdentificationIdentifier`                                      int(16) DEFAULT NULL,								
		`TradeDeliveryTermsDescriptionText`                                 varchar(200) DEFAULT NULL,								
		`ReferencedDocumentLineIdentifier`                                  int(4) DEFAULT NULL,							
		`ReferencedDocumentRevisionIdentificationIdentifier`                varchar(200) DEFAULT NULL,								
		`ReferencedDocumentInformationText`                                 varchar(200) DEFAULT NULL,								
		`ReferencedDocumentPurposeCode`                                     varchar(200) DEFAULT NULL,								
		`ReferencedDocumentSubtypeCode`                                     varchar(200) DEFAULT NULL,								
		`TradePriceTypeCode`                                                varchar(200) DEFAULT NULL,								
		`TradePriceChargeAmount`                                            varchar(200) DEFAULT NULL,								
		`TradePriceBasisQuantity`                                           varchar(200) DEFAULT NULL,								
		`TradePriceBasisUnitCose`                                           varchar(200) DEFAULT NULL,								
		`SupplyChainTradeDeliveryRequestedQuantity`                         varchar(200) DEFAULT NULL,								
		`SupplyChainTradeDeliveryPerPackageUnitQuantity`                    varchar(200) DEFAULT NULL,								
		`SupplyChainTradeDeliveryPackageQuantity`                           varchar(200) DEFAULT NULL,								
		`SupplyChainTradeDeliveryProductUnitQuantity`                       varchar(200) DEFAULT NULL,								
		`QuantityUnitCode`                                                  varchar(200) DEFAULT NULL,								
		`TradePartyIdentificationIdentifier`                                varchar(200) DEFAULT NULL,								
		`TradePartyGlobalIdentificationIdentifier`                          varchar(200) DEFAULT NULL,								
		`TradePartyNameText`                                                varchar(200) DEFAULT NULL,								
		`TradeContactPersonNameText`                                        varchar(200) DEFAULT NULL,								
		`TradeContactDepartmentNameText`                                    varchar(200) DEFAULT NULL,								
		`TradeAddressLineOneText`                                           varchar(200) DEFAULT NULL,								
		`TradeAddressLineOneText`                                           varchar(200) DEFAULT NULL,								
		`SupplyChainEventOccurrenceDateTime`                                varchar(200) DEFAULT NULL,								
		`LogisticsLocationIdentificationIdentifier`                         varchar(200) DEFAULT NULL,								
		`LogisticsLocationNameText`                                         varchar(200) DEFAULT NULL,								
		`TradeProductBuyerAssignedIdentificationIdentifier`                 varchar(200) DEFAULT NULL,								
		`TradeProductNameText`                                              varchar(200) DEFAULT NULL,								
		`TradeProduct`                                                      varchar(200) DEFAULT NULL,								
		`TradeProductTypeCode`                                              varchar(200) DEFAULT NULL,								
		`TradeProductEndItemTypeCode`                                       varchar(200) DEFAULT NULL,								
		`TradeProductSizeCode`                                              varchar(200) DEFAULT NULL,								
		`TradeProductSizeDescriptionText`                                   varchar(200) DEFAULT NULL,								
		`ProductCharacteristicIdentificationIdentifire`                     varchar(200) DEFAULT NULL,								
		`ProductCharacteristicTypeCode`                                     varchar(200) DEFAULT NULL,								
		`ProductCharacteristicDescriptionText`                              varchar(200) DEFAULT NULL,								
		`ProductCharacteristicTypeCode`                                     varchar(200) DEFAULT NULL,								
		`TradePartyIdentificationIdentifier`                                varchar(200) DEFAULT NULL,								
		`TradePartyNameText`                                                varchar(200) DEFAULT NULL,								
		`ReferencedDocumentIssuerAssignedIdentificationIdentifier`          varchar(200) DEFAULT NULL,								
		`ReferencedDocumentRevisionIdentificationIdentifier`                varchar(200) DEFAULT NULL,								
		`ReferencedDocumentNameText`                                        varchar(200) DEFAULT NULL,								
		`ReferencedDocumentInformationText`                                 varchar(200) DEFAULT NULL,								
		`ReferencedDocumentAttachmentBinaryObject`                          varchar(200) DEFAULT NULL,								
		`ReferencedLogisticsPackageItemQuantity`                            varchar(200) DEFAULT NULL,								
		`ReferencedLogisticsQuantityUnitCode`                               varchar(200) DEFAULT NULL,								
		`ReferencedLogisticsTypeCode`                                       varchar(200) DEFAULT NULL,								


    PRIMARY KEY (`ReferencedDocumentIssuerAssignedIdentificationIdentifier`),

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;